-- =========================================================
-- 1. icons テーブルを作成
-- =========================================================

CREATE TABLE icons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(50) NOT NULL,

    gender VARCHAR(20) NOT NULL,

    generation VARCHAR(20) NOT NULL,

    image_path VARCHAR(500) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()

);


-- =========================================================
-- 2. users に gender を追加
-- =========================================================

ALTER TABLE users
ADD COLUMN gender VARCHAR(20);


-- =========================================================
-- 3. users に generation を追加
-- =========================================================

ALTER TABLE users
ADD COLUMN generation VARCHAR(20);


-- =========================================================
-- 4. users に icon_id を追加
-- =========================================================

ALTER TABLE users
ADD COLUMN icon_id BIGINT;


-- =========================================================
-- 5. users.icon_id → icons.id の外部キー
-- =========================================================

ALTER TABLE users
ADD CONSTRAINT users_icon_id_fkey
FOREIGN KEY (icon_id)
REFERENCES icons(id)
ON DELETE RESTRICT
ON UPDATE CASCADE;