-- 世代別変換SNS: 全テーブル作成SQL
-- Supabase SQL Editorで上から順番に実行してください。

CREATE TABLE public.style_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  default_style_id BIGINT NOT NULL
    REFERENCES public.style_profiles(id) ON DELETE RESTRICT,
  google_sub VARCHAR(255) UNIQUE,
  guest_uuid UUID UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_identity_check CHECK (
    (google_sub IS NOT NULL AND guest_uuid IS NULL)
    OR (google_sub IS NULL AND guest_uuid IS NOT NULL)
  )
);

CREATE TABLE public.reaction_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  code VARCHAR(30) NOT NULL UNIQUE,
  icon VARCHAR(10) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_post_id BIGINT
    REFERENCES public.posts(id) ON DELETE RESTRICT,
  author_id BIGINT NOT NULL
    REFERENCES public.users(id) ON DELETE RESTRICT,
  original_text TEXT NOT NULL,
  converted_text TEXT NOT NULL,
  like_count INTEGER NOT NULL DEFAULT 0 CHECK (like_count >= 0),
  laugh_count INTEGER NOT NULL DEFAULT 0 CHECK (laugh_count >= 0),
  sad_count INTEGER NOT NULL DEFAULT 0 CHECK (sad_count >= 0),
  reply_count INTEGER NOT NULL DEFAULT 0 CHECK (reply_count >= 0),
  style_type_id BIGINT NOT NULL
    REFERENCES public.style_profiles(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.post_reactions (
  post_id BIGINT NOT NULL
    REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL
    REFERENCES public.users(id) ON DELETE CASCADE,
  reaction_type_id BIGINT NOT NULL
    REFERENCES public.reaction_types(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, user_id)
);

CREATE TABLE public.images_paths (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL
    REFERENCES public.posts(id) ON DELETE CASCADE,
  path VARCHAR(500) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.hashtags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_name VARCHAR(100) NOT NULL UNIQUE,
  usage_count INTEGER NOT NULL DEFAULT 0 CHECK (usage_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.post_hashtags (
  post_id BIGINT NOT NULL
    REFERENCES public.posts(id) ON DELETE CASCADE,
  hashtag_id BIGINT NOT NULL
    REFERENCES public.hashtags(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, hashtag_id)
);

CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id BIGINT NOT NULL
    REFERENCES public.users(id) ON DELETE CASCADE,
  actor_id BIGINT
    REFERENCES public.users(id) ON DELETE SET NULL,
  notification_type VARCHAR(30) NOT NULL,
  post_id BIGINT
    REFERENCES public.posts(id) ON DELETE CASCADE,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT notifications_type_check CHECK (
    notification_type IN ('reply', 'reaction')
  ),
  CONSTRAINT notifications_actor_check CHECK (
    actor_id IS NULL OR recipient_id <> actor_id
  )
);

CREATE INDEX posts_created_at_idx
  ON public.posts (created_at DESC);

CREATE INDEX posts_author_id_idx
  ON public.posts (author_id);

CREATE INDEX posts_parent_post_id_idx
  ON public.posts (parent_post_id);

CREATE INDEX post_reactions_user_id_idx
  ON public.post_reactions (user_id);

CREATE INDEX images_paths_post_id_idx
  ON public.images_paths (post_id);

CREATE INDEX post_hashtags_hashtag_id_idx
  ON public.post_hashtags (hashtag_id);

CREATE INDEX notifications_recipient_created_at_idx
  ON public.notifications (recipient_id, created_at DESC);

CREATE INDEX notifications_unread_idx
  ON public.notifications (recipient_id, is_read, created_at DESC);

INSERT INTO public.style_profiles (name)
VALUES
  ('赤ちゃん'),
  ('小学生'),
  ('中学生'),
  ('高校生'),
  ('大学生'),
  ('アラサー'),
  ('中年'),
  ('老人');

INSERT INTO public.reaction_types (name, code, icon)
VALUES
  ('いいね', 'like', '👍'),
  ('笑', 'laugh', '😂'),
  ('悲しい', 'sad', '😢');

